#!/bin/bash -e
### BEGIN INIT INFO
# Provides:          live-update-bootmenu
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Updates the [sys/iso]linux menu config
# Description:       Updates the [sys/iso]linux menu config
### END INIT INFO
#
# description: Updates the [sys/iso]linux menu config
#

IMAGE_DIR="/live/image"

# the image directory must be remounted writeable
# so that we can edit the config files
if ! mount -o remount,rw ${IMAGE_DIR}
then
	# it's ok, system was probably booted from iso...
	exit 0
fi

# determine correct configuration directory
if [ -d ${IMAGE_DIR}/isolinux/ ]
then
	CONFIG_DIR="${IMAGE_DIR}/isolinux"
elif [ -d ${IMAGE_DIR}/syslinux/ ]
then
	CONFIG_DIR="${IMAGE_DIR}/syslinux"
else
	echo "no supported configuration found"
	exit 1
fi

# check writability of configuration directory
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ! This test only works reliably with bash on      !
# ! read-only filesystems! Therefore, do not change !
# ! the first line with /bin/bash in this script!   !
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
if [ ! -w ${CONFIG_DIR} ]
then
	# it's ok, system was probably booted from iso...
	exit 0
fi

XMLBOOT_CONFIG="${CONFIG_DIR}/xmlboot.config"

# get current append line
APPEND="$(cat /proc/cmdline | sed -e 's| BOOT_IMAGE=.*||')"

# update configs in xmlboot config file
update_config()
{
	cat ${XMLBOOT_CONFIG} | \
	xmlstarlet ed -d "/xmlboot/configs/config[@id='${1}']/option/@selected" | \
	xmlstarlet ed -i "/xmlboot/configs/config[@id='${1}']/option[@append='${2}']" \
		--type attr -n selected -v true > ${XMLBOOT_CONFIG}.tmp
	mv ${XMLBOOT_CONFIG}.tmp ${XMLBOOT_CONFIG}
}
for _PARAMETER in ${APPEND}
do
	case "${_PARAMETER}" in
		locales=*)
			update_config "language" "${_PARAMETER}"
			;;

		keyboard-layouts=*)
			update_config "keyboard" "${_PARAMETER}"
			;;

		desktop*)
			LIVE_DESKTOP="${_PARAMETER#*desktop=}"
			case "${LIVE_DESKTOP}" in
				kde)
					update_config "desktop" "desktop=kde nottyautologin"
					;;
				gnome)
					update_config "desktop" "desktop=gnome nottyautologin"
					;;
				lxde)
					update_config "desktop" "desktop=lxde nottyautologin"
					;;
				sugar)
					update_config "desktop" "desktop=sugar nottyautologin"
					;;
				no)
					update_config "desktop" "desktop=no"
			esac
	esac
done

# update options in xmlboot config file
deselect_option()
{
	cat ${XMLBOOT_CONFIG} | \
	xmlstarlet ed -d "/xmlboot/options/option[@id='${1}']/@selected" \
		> ${XMLBOOT_CONFIG}.tmp
	mv ${XMLBOOT_CONFIG}.tmp ${XMLBOOT_CONFIG}
}

select_option()
{
	cat ${XMLBOOT_CONFIG} | \
	xmlstarlet ed -d "/xmlboot/options/option[@id='${1}']/@selected" | \
	xmlstarlet ed -i "/xmlboot/options/option[@id='${1}']" \
		--type attr -n selected -v true > ${XMLBOOT_CONFIG}.tmp
	mv ${XMLBOOT_CONFIG}.tmp ${XMLBOOT_CONFIG}
}

update_selected_option()
{
	if grep -q "${1}" /proc/cmdline
	then
		select_option "${2}"
	else
		deselect_option "${2}"
	fi
}
update_selected_option "swapon" "swap_partition"
update_selected_option "swapfile=auto" "swap_file"
update_selected_option "debug=1" "debug"

update_nonselected_option()
{
	if ! grep -q "${1}" /proc/cmdline
	then
		select_option "${2}"
	else
		deselect_option "${2}"
	fi
}
update_nonselected_option "persistent" "persistence"
update_nonselected_option "quiet splash" "messages"
update_nonselected_option "nolapic_timer" "lapic_timer"
update_nonselected_option "nohz=off" "dynamic_ticks"

CUSTOM_OPTIONS="$(cat /proc/cmdline | sed 's|.*custom_options \(.*\)|\1|1')"
cat ${XMLBOOT_CONFIG} | \
xmlstarlet ed -u "/xmlboot/custom_options/@text" -v "${CUSTOM_OPTIONS}" > ${XMLBOOT_CONFIG}.tmp
mv ${XMLBOOT_CONFIG}.tmp ${XMLBOOT_CONFIG}

# special handling for PAE
if grep -q initrd2 /proc/cmdline
then
	select_option "pae"
else
	deselect_option "pae"
fi

# remount /live/image read-only
mount -o remount,ro /live/image/
